source 'https://cdn.cocoapods.org/'
project './{{appName}}.xcodeproj'

platform :ios, '10.0'

plugin 'cocoapods-lynx-library'

lynx_version = '3.9.0'

target '{{appName}}' do
  use_lynx_library!

  pod 'Lynx', lynx_version, :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '3.8.0-alpha.6', :subspecs => ['quickjs', 'napi']

  pod 'LynxService', lynx_version, :subspecs => [
      'Image',
      'Log',
      'Http',
      'Devtool',
  ]

  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
  pod 'LynxDevtool', lynx_version
end
