source 'https://cdn.cocoapods.org/'
project './{{appName}}.xcodeproj'

platform :ios, '10.0'

plugin 'cocoapods-lynx-extension'

lynx_version = '4.0.0-nightly.202605271320.48.gb56a1591'

target '{{appName}}' do
  use_lynx_extension!

  pod 'Lynx', lynx_version, :subspecs => [
    'Framework',
  ]

  pod 'PrimJS', '3.8.0-alpha.6', :subspecs => ['quickjs', 'napi']

  pod 'LynxService', lynx_version, :subspecs => [
      'Image',
      'Log',
      'Http',
      'Devtool',
  ]

  # ImageService dependencies:
  pod 'SDWebImage','5.15.5'
  pod 'SDWebImageWebPCoder', '0.11.0'
  pod 'LynxDevtool', lynx_version
end
